$! define /group     TESTDEFINE_GROUP        DISK_1:[CABS_USR.CABS_SS.TMP.CRTING_AUTO_5JUL12_0022]
$ define /process   TESTDEFINE_PROCESS      DISK_1:[CABS_USR.CABS_SS.TMP.CRTING_AUTO_5JUL12_0022]
$ define            TESTDEFINE_EMPTY        DISK_1:[CABS_USR.CABS_SS.TMP.CRTING_AUTO_5JUL12_0022]
